apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: authentication
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DATABASE_URL
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: JWT_SECRET_KEY
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_ROOT_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: authentication
spec:
  type: LoadBalancer
  selector:
    app: authentication
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000