apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  MONGO_URL: "mongodb://mongo:27017"
  MONGO_DB: "fund"
  REDIS_URL: "redis://redis:6379"
  DATABASE_URL: "authenticationdb"

---
apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  JWT_SECRET_KEY: "super-secret-key-change-in-production"