apiVersion: batch/v1
kind: Job
metadata:
  name: authenticationdbmigration
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: authenticationdbmigration
          image: authenticationdbmigration
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DATABASE_URL
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_ROOT_PASSWORD